# Generated by Django 6.0.2 on 2026-07-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_account_options_account_code_account_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(help_text="Agrupador del tag, ej: 'Naturaleza del gasto', 'Centro de Costo', 'Área'", max_length=50)),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='accounting.accounttag'),
        ),
    ]
